import {
  GemStoneClass,
  GemStoneSelector,
  metadataFor,
  OOP_FALSE,
  renderGeneratedFunction,
  renderGeneratedModule,
  sendGenerated,
  Session,
  smallintToOop,
  type Oop,
} from "../src/index.ts";
import { MockGciRuntime } from "../src/testing/mock-runtime.ts";

const registeredTests: Array<() => Promise<void>> = [];

test("sendGenerated uses the standard argument marshalling path", async () => {
  const runtime = new MockGciRuntime();
  const session = await Session.connect({ username: "u", password: "p", runtime });

  await sendGenerated(session, "Booking", "find:active:count:", ["Ada", false, 3]);

  const perform = runtime.calls.findLast((call) => call.method === "perform");
  if (!perform) throw new Error("sendGenerated should call perform");
  const args = perform.args[2] as unknown[];

  assert(runtime.calls.some((call) => call.method === "newString" && call.args[0] === "Ada"), "string arguments should use newString");
  assertEqual(args[1], OOP_FALSE);
  assertEqual(args[2], smallintToOop(3));

  await session.logout();
});

test("sendGenerated can return raw OOPs without result marshalling", async () => {
  const runtime = new MockGciRuntime();
  const session = await Session.connect({ username: "u", password: "p", runtime });

  const raw = await sendGenerated(session, "Booking", "find:", ["B-1"], "oop");

  assertEqual(raw, 0x3000n as Oop);
  assert(runtime.calls.some((call) => call.method === "newString" && call.args[0] === "B-1"), "raw wrappers should still marshal arguments");
  assert(!runtime.calls.some((call) => call.method === "fetchClass"), "raw wrappers should not marshal the return value");

  await session.logout();
});

test("sendGenerated can return retained typed object handles", async () => {
  const runtime = new MockGciRuntime();
  const session = await Session.connect({ username: "u", password: "p", runtime });

  const found = await sendGenerated(session, "Booking", "find:", ["B-2"], "object");

  assertEqual(found.session, session);
  assertEqual(found.oop, 0x3000n as Oop);
  assert(runtime.calls.some((call) => call.method === "newString" && call.args[0] === "B-2"), "object wrappers should still marshal arguments");

  await found.release();
  assert(runtime.calls.some((call) => call.method === "addOopToExportSet" && call.args[0] === found.oop), "object wrappers should retain the returned handle");
  await session.logout();
});

test("renderGeneratedFunction emits value-returning wrappers without dangling parameters", () => {
  assertEqual(renderGeneratedFunction({
    exportedName: "currentStatus",
    className: "Booking",
    selector: "currentStatus",
    argNames: [],
  }), [
    "export async function currentStatus(session) {",
    "  const receiver = await session.resolveSymbol(\"Booking\");",
    "  return session.performValueWith(receiver, \"currentStatus\");",
    "}",
    "",
  ].join("\n"));

  assertEqual(renderGeneratedFunction({
    exportedName: "findBooking",
    className: "Booking",
    selector: "find:active:",
    argNames: ["id", "active"],
  }), [
    "export async function findBooking(session, id, active) {",
    "  const receiver = await session.resolveSymbol(\"Booking\");",
    "  return session.performValueWith(receiver, \"find:active:\", id, active);",
    "}",
    "",
  ].join("\n"));
});

test("renderGeneratedFunction emits raw-OOP and object-returning wrappers", () => {
  assertEqual(renderGeneratedFunction({
    exportedName: "rawBooking",
    className: "Booking",
    selector: "find:",
    argNames: ["id"],
    returnKind: "oop",
  }), [
    "export async function rawBooking(session, id) {",
    "  const receiver = await session.resolveSymbol(\"Booking\");",
    "  return session.performWith(receiver, \"find:\", id);",
    "}",
    "",
  ].join("\n"));

  assertEqual(renderGeneratedFunction({
    exportedName: "findBookingObject",
    className: "Booking",
    selector: "find:",
    argNames: ["id"],
    returnKind: "object",
  }), [
    "export async function findBookingObject(session, id) {",
    "  return session.classRef(\"Booking\").sendObject(\"find:\", id);",
    "}",
    "",
  ].join("\n"));
});

test("renderGeneratedModule emits stable multi-wrapper source", () => {
  assertEqual(renderGeneratedModule({
    functions: [
      {
        exportedName: "currentStatus",
        className: "Booking",
        selector: "currentStatus",
        argNames: [],
      },
      {
        exportedName: "findBookingObject",
        className: "Booking",
        selector: "find:",
        argNames: ["id"],
        returnKind: "object",
      },
    ],
  }), [
    "// Generated by gemstone-js codegen. Do not edit.",
    "",
    "export async function currentStatus(session) {",
    "  const receiver = await session.resolveSymbol(\"Booking\");",
    "  return session.performValueWith(receiver, \"currentStatus\");",
    "}",
    "",
    "export async function findBookingObject(session, id) {",
    "  return session.classRef(\"Booking\").sendObject(\"find:\", id);",
    "}",
    "",
  ].join("\n"));

  assertEqual(renderGeneratedModule({
    banner: false,
    functions: [{
      exportedName: "rawBooking",
      className: "Booking",
      selector: "find:",
      argNames: ["id"],
      returnKind: "oop",
    }],
  }), [
    "export async function rawBooking(session, id) {",
    "  const receiver = await session.resolveSymbol(\"Booking\");",
    "  return session.performWith(receiver, \"find:\", id);",
    "}",
    "",
  ].join("\n"));
});

test("renderGeneratedModule rejects invalid manifests", () => {
  assertThrows(() => renderGeneratedModule({ functions: "oops" as never }));
});

test("renderGeneratedFunction rejects unsafe JavaScript identifiers", () => {
  assertThrows(() => renderGeneratedFunction({
    exportedName: "bad;name",
    className: "Booking",
    selector: "find:",
    argNames: ["id"],
  }));
  assertThrows(() => renderGeneratedFunction({
    exportedName: "findBooking",
    className: "Booking",
    selector: "find:",
    argNames: ["class"],
  }));
  assertThrows(() => renderGeneratedFunction({
    exportedName: "findBooking",
    className: "Booking",
    selector: "find:again:",
    argNames: ["id", "id"],
  }));
  assertThrows(() => renderGeneratedFunction({
    exportedName: "findBooking",
    className: "Booking",
    selector: "find:",
    argNames: ["id"],
    returnKind: "record" as never,
  }));
});

test("decorator helpers retain class and selector metadata", () => {
  class Booking {}

  GemStoneSelector("markPaidAt:")(Booking.prototype, "markPaidAt", undefined as never);
  GemStoneClass("OkzBooking")(Booking);

  const metadata = metadataFor(Booking);
  if (!metadata) throw new Error("GemStoneClass should register metadata");
  assertEqual(metadata.className, "OkzBooking");
  assertEqual(metadata.selectors.get("markPaidAt"), "markPaidAt:");
});

for (const run of registeredTests) {
  await run();
}

function test(name: string, fn: () => void | Promise<void>): void {
  registeredTests.push(async () => {
    try {
      await fn();
    } catch (error) {
      if (error instanceof Error) {
        error.message = `${name}: ${error.message}`;
      }
      throw error;
    }
  });
}

function assert(value: unknown, message: string): void {
  if (!value) throw new Error(message);
}

function assertEqual<T>(actual: T, expected: T): void {
  if (actual !== expected) {
    throw new Error(`expected ${String(expected)}, got ${String(actual)}`);
  }
}

function assertThrows(fn: () => unknown): void {
  try {
    fn();
  } catch {
    return;
  }
  throw new Error("expected function to throw");
}
