import { execFile } from "node:child_process";
import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import assert from "node:assert/strict";
import test from "node:test";

const codegenScript = fileURLToPath(new URL("../scripts/codegen.mjs", import.meta.url));
const scanScript = fileURLToPath(new URL("../scripts/scan-codegen.mjs", import.meta.url));
const manifest = fileURLToPath(new URL("../examples/codegen.manifest.json", import.meta.url));

test("codegen CLI writes output and checks generated files", async () => {
  const dir = await mkdtemp(join(tmpdir(), "gemstone-js-codegen-"));
  try {
    const outputPath = join(dir, "booking.generated.ts");

    await execNode([codegenScript, manifest, outputPath]);
    const generated = await readFile(outputPath, "utf8");
    assert.match(generated, /Generated by gemstone-js codegen/);
    assert.match(generated, /findBookingObject/);

    const check = await execNode([codegenScript, "--check", manifest, outputPath]);
    assert.match(check.stdout, /Generated output is up to date/);

    await writeFile(outputPath, "stale\n");
    await assert.rejects(
      execNode([codegenScript, "--check", manifest, outputPath]),
      (error: unknown) => {
        assert(error && typeof error === "object" && "stderr" in error);
        assert.match(String((error as { stderr: string }).stderr), /out of date/);
        return true;
      },
    );
  } finally {
    await rm(dir, { recursive: true, force: true });
  }
});

test("codegen scanner emits manifests from decorated classes", async () => {
  const dir = await mkdtemp(join(tmpdir(), "gemstone-js-codegen-scan-"));
  try {
    const sourcePath = join(dir, "booking.ts");
    await writeFile(sourcePath, [
      "import { GemStoneClass, GemStoneSelector, type Session, type TypedOop } from \"gemstone-js\";",
      "interface Booking {}",
      "@GemStoneClass(\"Booking\")",
      "class BookingModel {",
      "  currentStatus(session: Session): Promise<string> {}",
      "  @GemStoneSelector(\"find:active:\")",
      "  static findBooking(session: Session, id: string, active: boolean): Promise<TypedOop<Booking>> {}",
      "}",
      "",
    ].join("\n"));

    const { stdout } = await execNode([scanScript, sourcePath]);
    const scanned = JSON.parse(stdout);

    assert.equal(scanned.functions.length, 2);
    assert.deepEqual(scanned.functions[0], {
      exportedName: "currentStatus",
      className: "Booking",
      selector: "currentStatus",
      argNames: [],
      sessionType: "Session",
      returnType: "string",
    });
    assert.deepEqual(scanned.functions[1], {
      exportedName: "findBooking",
      className: "Booking",
      selector: "find:active:",
      argNames: ["id", "active"],
      argTypes: ["string", "boolean"],
      sessionType: "Session",
      returnType: "TypedOop<Booking>",
    });
  } finally {
    await rm(dir, { recursive: true, force: true });
  }
});

function execNode(args: string[]): Promise<{ stdout: string; stderr: string }> {
  return new Promise((resolve, reject) => {
    execFile(process.execPath, args, { encoding: "utf8" }, (error, stdout, stderr) => {
      if (error) {
        reject(Object.assign(error, { stdout, stderr }));
      } else {
        resolve({ stdout, stderr });
      }
    });
  });
}
