import { execFile } from "node:child_process";
import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import assert from "node:assert/strict";
import test from "node:test";

const codegenScript = fileURLToPath(new URL("../scripts/codegen.mjs", import.meta.url));
const scanScript = fileURLToPath(new URL("../scripts/scan-codegen.mjs", import.meta.url));
const manifest = fileURLToPath(new URL("../examples/codegen.manifest.json", import.meta.url));
const decoratorSource = fileURLToPath(new URL("../examples/booking.decorators.ts", import.meta.url));
const decoratorGenerated = fileURLToPath(new URL("../examples/booking.decorators.generated.ts", import.meta.url));

test("codegen CLI writes output and checks generated files", async () => {
  const dir = await mkdtemp(join(tmpdir(), "gemstone-js-codegen-"));
  try {
    const outputPath = join(dir, "booking.generated.ts");

    await execNode([codegenScript, manifest, outputPath]);
    const generated = await readFile(outputPath, "utf8");
    assert.match(generated, /Generated by gemstone-js codegen/);
    assert.match(generated, /findBookingObject/);

    const check = await execNode([codegenScript, "--check", manifest, outputPath]);
    assert.match(check.stdout, /Generated output is up to date/);

    await writeFile(outputPath, "stale\n");
    await assert.rejects(
      execNode([codegenScript, "--check", manifest, outputPath]),
      (error: unknown) => {
        assert(error && typeof error === "object" && "stderr" in error);
        assert.match(String((error as { stderr: string }).stderr), /out of date/);
        return true;
      },
    );
  } finally {
    await rm(dir, { recursive: true, force: true });
  }
});

test("codegen scanner emits manifests from decorated classes", async () => {
  const dir = await mkdtemp(join(tmpdir(), "gemstone-js-codegen-scan-"));
  try {
    const sourcePath = join(dir, "booking.ts");
    await writeFile(sourcePath, [
      "import { GemStoneClass, GemStoneSelector, type Oop, type Session, type TypedOop } from \"gemstone-js\";",
      "import type { Booking } from \"./booking-types.ts\";",
      "@GemStoneClass(\"Booking\")",
      "class BookingModel {",
      "  currentStatus(session: Session): Promise<string> {}",
      "  @GemStoneSelector(\"find:active:\")",
      "  static findBooking(session: Session, id: string, active: boolean): Promise<TypedOop<Booking>> {}",
      "  static rawBooking(session: Session, id: string): Promise<Oop> {}",
      "}",
      "",
    ].join("\n"));

    const { stdout } = await execNode([scanScript, sourcePath]);
    const scanned = JSON.parse(stdout);

    assert.deepEqual(scanned.imports, [
      {
        from: "gemstone-js",
        typeNames: ["Session", "TypedOop", "Oop"],
      },
      {
        from: "./booking-types.ts",
        typeNames: ["Booking"],
      },
    ]);
    assert.equal(scanned.functions.length, 3);
    assert.deepEqual(scanned.functions[0], {
      exportedName: "currentStatus",
      className: "Booking",
      selector: "currentStatus",
      argNames: [],
      sessionType: "Session",
      returnType: "string",
    });
    assert.deepEqual(scanned.functions[1], {
      exportedName: "findBooking",
      className: "Booking",
      selector: "find:active:",
      argNames: ["id", "active"],
      argTypes: ["string", "boolean"],
      sessionType: "Session",
      returnType: "TypedOop<Booking>",
      returnKind: "object",
    });
    assert.deepEqual(scanned.functions[2], {
      exportedName: "rawBooking",
      className: "Booking",
      selector: "rawBooking:",
      argNames: ["id"],
      argTypes: ["string"],
      sessionType: "Session",
      returnType: "Oop",
      returnKind: "oop",
    });

    const moduleOutput = await execNode([scanScript, "--module", sourcePath]);
    assert.match(moduleOutput.stdout, /import type \{ Session, TypedOop, Oop \} from "gemstone-js";/);
    assert.match(moduleOutput.stdout, /sendObject\("find:active:", id, active\)/);
    assert.match(moduleOutput.stdout, /performWith\(receiver, "rawBooking:", id\)/);

    const outputPath = join(dir, "booking.generated.ts");
    await execNode([scanScript, "--module", "--out", outputPath, sourcePath]);
    const check = await execNode([scanScript, "--module", "--out", outputPath, "--check", sourcePath]);
    assert.match(check.stdout, /Generated module output is up to date/);
  } finally {
    await rm(dir, { recursive: true, force: true });
  }
});

test("codegen scanner handles same-line decorators and nested parameter types", async () => {
  const dir = await mkdtemp(join(tmpdir(), "gemstone-js-codegen-scan-inline-"));
  try {
    const sourcePath = join(dir, "inline-booking.ts");
    await writeFile(sourcePath, [
      "import { GemStoneClass, GemStoneSelector, type Session } from \"gemstone-js\";",
      "@GemStoneClass(\"Booking\") class InlineBookingModel {",
      "  @GemStoneSelector(\"findBy:options:\") public static async findBy(session: Session, id: string, options: Record<string, boolean>): Promise<string> {}",
      "  @GemStoneSelector(\"status\") protected override status(session: Session): Promise<string> {}",
      "}",
      "",
    ].join("\n"));

    const { stdout } = await execNode([scanScript, sourcePath]);
    const scanned = JSON.parse(stdout);

    assert.deepEqual(scanned.imports, [
      {
        from: "gemstone-js",
        typeNames: ["Session"],
      },
    ]);
    assert.deepEqual(scanned.functions, [
      {
        exportedName: "findBy",
        className: "Booking",
        selector: "findBy:options:",
        argNames: ["id", "options"],
        argTypes: ["string", "Record<string, boolean>"],
        sessionType: "Session",
        returnType: "string",
      },
      {
        exportedName: "status",
        className: "Booking",
        selector: "status",
        argNames: [],
        sessionType: "Session",
        returnType: "string",
      },
    ]);
  } finally {
    await rm(dir, { recursive: true, force: true });
  }
});

test("codegen scanner resolves decorator/type aliases and skips overload signatures", async () => {
  const dir = await mkdtemp(join(tmpdir(), "gemstone-js-codegen-scan-alias-"));
  try {
    const sourcePath = join(dir, "alias-booking.ts");
    await writeFile(sourcePath, [
      "import { GemStoneClass as GSClass, GemStoneSelector as GSSelector, type Session as GSSession, type TypedOop } from \"gemstone-js\";",
      "import type { Booking as BookingRecord } from \"./booking-types.ts\";",
      "@GSClass(\"Booking\")",
      "class AliasBookingModel {",
      "  findBooking(session: GSSession, id: string): Promise<TypedOop<BookingRecord>>;",
      "  @GSSelector(\"find:\")",
      "  findBooking(session: GSSession, id: string): Promise<TypedOop<BookingRecord>> {",
      "    throw new Error(\"scanner fixture only\");",
      "  }",
      "}",
      "",
    ].join("\n"));

    const { stdout } = await execNode([scanScript, sourcePath]);
    const scanned = JSON.parse(stdout);

    assert.deepEqual(scanned.imports, [
      {
        from: "gemstone-js",
        typeNames: ["TypedOop"],
        typeSpecifiers: [{ name: "Session", alias: "GSSession" }],
      },
      {
        from: "./booking-types.ts",
        typeSpecifiers: [{ name: "Booking", alias: "BookingRecord" }],
      },
    ]);
    assert.deepEqual(scanned.functions, [
      {
        exportedName: "findBooking",
        className: "Booking",
        selector: "find:",
        argNames: ["id"],
        argTypes: ["string"],
        sessionType: "GSSession",
        returnType: "TypedOop<BookingRecord>",
        returnKind: "object",
      },
    ]);

    const moduleOutput = await execNode([scanScript, "--module", sourcePath]);
    assert.match(moduleOutput.stdout, /import type \{ TypedOop, Session as GSSession \} from "gemstone-js";/);
    assert.match(moduleOutput.stdout, /import type \{ Booking as BookingRecord \} from "\.\/booking-types\.ts";/);
    assert.match(moduleOutput.stdout, /export async function findBooking\(session: GSSession, id: string\): Promise<TypedOop<BookingRecord>>/);
  } finally {
    await rm(dir, { recursive: true, force: true });
  }
});

test("codegen scanner recognizes gemstone-js namespace decorators only", async () => {
  const dir = await mkdtemp(join(tmpdir(), "gemstone-js-codegen-scan-namespace-"));
  try {
    const sourcePath = join(dir, "namespace-booking.ts");
    await writeFile(sourcePath, [
      "import * as Gem from \"gemstone-js\";",
      "import type { Session } from \"gemstone-js\";",
      "const Other = Gem;",
      "@Other.GemStoneClass(\"Ignored\")",
      "class IgnoredBookingModel {",
      "  ignored(session: Session): Promise<string> { throw new Error(\"ignored\"); }",
      "}",
      "@Gem.GemStoneClass(\"Booking\")",
      "class NamespaceBookingModel {",
      "  @Gem.GemStoneSelector(\"status\")",
      "  status(session: Session): Promise<string> { throw new Error(\"scanner fixture only\"); }",
      "}",
      "",
    ].join("\n"));

    const { stdout } = await execNode([scanScript, sourcePath]);
    const scanned = JSON.parse(stdout);

    assert.deepEqual(scanned.functions, [
      {
        exportedName: "status",
        className: "Booking",
        selector: "status",
        argNames: [],
        sessionType: "Session",
        returnType: "string",
      },
    ]);
  } finally {
    await rm(dir, { recursive: true, force: true });
  }
});

test("codegen scanner preserves namespace type imports used by wrapper signatures", async () => {
  const dir = await mkdtemp(join(tmpdir(), "gemstone-js-codegen-scan-type-namespace-"));
  try {
    const sourcePath = join(dir, "namespace-types.ts");
    await writeFile(sourcePath, [
      "import { GemStoneClass, GemStoneSelector, type Session, type TypedOop } from \"gemstone-js\";",
      "import type * as BookingTypes from \"./booking-types.ts\";",
      "@GemStoneClass(\"Booking\")",
      "class BookingModel {",
      "  @GemStoneSelector(\"find:\")",
      "  static findBooking(session: Session, id: string): Promise<TypedOop<BookingTypes.Booking>> {",
      "    throw new Error(\"scanner fixture only\");",
      "  }",
      "}",
      "",
    ].join("\n"));

    const { stdout } = await execNode([scanScript, sourcePath]);
    const scanned = JSON.parse(stdout);

    assert.deepEqual(scanned.imports, [
      {
        from: "gemstone-js",
        typeNames: ["Session", "TypedOop"],
      },
      {
        from: "./booking-types.ts",
        typeNamespaceName: "BookingTypes",
      },
    ]);
    assert.equal(scanned.functions[0].returnType, "TypedOop<BookingTypes.Booking>");

    const moduleOutput = await execNode([scanScript, "--module", sourcePath]);
    assert.match(moduleOutput.stdout, /import type \* as BookingTypes from "\.\/booking-types\.ts";/);
    assert.match(moduleOutput.stdout, /Promise<TypedOop<BookingTypes\.Booking>>/);
  } finally {
    await rm(dir, { recursive: true, force: true });
  }
});

test("codegen scanner reports TypeScript parse errors without a stack trace", async () => {
  const dir = await mkdtemp(join(tmpdir(), "gemstone-js-codegen-scan-parse-"));
  try {
    const sourcePath = join(dir, "broken.ts");
    await writeFile(sourcePath, [
      "import { GemStoneClass, type Session } from \"gemstone-js\";",
      "@GemStoneClass(\"Booking\")",
      "class BrokenBookingModel {",
      "  status(session: Session): Promise<string> {",
      "}",
      "",
    ].join("\n"));

    await assert.rejects(
      execNode([scanScript, sourcePath]),
      (error: unknown) => {
        assert(error && typeof error === "object" && "stderr" in error);
        const stderr = String((error as { stderr: string }).stderr);
        assert.match(stderr, /TypeScript parse error/);
        assert.match(stderr, /broken\.ts:\d+:\d+/);
        assert(!stderr.includes("at scanSource"), "parse errors should not include scanner stack traces");
        return true;
      },
    );
  } finally {
    await rm(dir, { recursive: true, force: true });
  }
});

test("codegen scanner checks committed decorated-source wrapper output", async () => {
  const check = await execNode([
    scanScript,
    "--module",
    "--check",
    "--out",
    decoratorGenerated,
    decoratorSource,
  ]);
  assert.match(check.stdout, /Generated module output is up to date/);
});

function execNode(args: string[]): Promise<{ stdout: string; stderr: string }> {
  return new Promise((resolve, reject) => {
    execFile(process.execPath, args, { encoding: "utf8" }, (error, stdout, stderr) => {
      if (error) {
        reject(Object.assign(error, { stdout, stderr }));
      } else {
        resolve({ stdout, stderr });
      }
    });
  });
}
