// Generated by gemstone-js codegen. Do not edit.

import type { Session, TypedOop } from "gemstone-js";
import type { Booking as BookingRecord } from "./booking.ts";

export async function currentBookingStatus(session: Session): Promise<string> {
  const receiver = await session.resolveSymbol("Booking");
  return session.performValueWith(receiver, "currentStatus");
}

export async function findBookingObject(session: Session, id: string): Promise<TypedOop<BookingRecord>> {
  return session.classRef("Booking").sendObject("find:", id);
}
