// Generated by gemstone-js codegen. Do not edit.

import type { Oop, Session, TypedOop } from "gemstone-js";
import type { Booking as BookingRecord } from "./booking.ts";

export async function currentBookingStatus(session: Session): Promise<string> {
  const receiver = await session.resolveSymbol("Booking");
  return session.performValueWith(receiver, "currentStatus");
}

export async function findBookingObject(session: Session, id: string): Promise<TypedOop<BookingRecord>> {
  return session.classRef("Booking").sendObject("find:", id);
}

export async function findBookingsByTags(session: Session, tags: readonly string[], filters: Record<string, string | number | boolean>): Promise<TypedOop<BookingRecord>> {
  return session.classRef("Booking").sendObject("findWithTags:filters:", tags, filters);
}

export async function findBookingOopByTags(session: Session, tags: readonly string[]): Promise<Oop> {
  const receiver = await session.resolveSymbol("Booking");
  return session.performWith(receiver, "findOopWithTags:", tags);
}
