// Generated by gemstone-js codegen. Do not edit.

import type { MarshalledValue, Oop, Session, TypedOop } from "../../src/index.ts";

export async function generatedObjectPrintString(session: Session): Promise<MarshalledValue> {
  const receiver = await session.resolveSymbol("Object");
  return session.performValueWith(receiver, "printString");
}

export async function generatedObjectClassOop(session: Session): Promise<Oop> {
  const receiver = await session.resolveSymbol("Object");
  return session.performWith(receiver, "yourself");
}

export async function generatedNewObject(session: Session): Promise<TypedOop<unknown>> {
  return session.classRef("Object").sendObject("new");
}
