import type { GemStoneArgument, MarshalledValue, Session, TypedOop } from "./client.ts";
import type { Oop } from "./oop.ts";

export type GeneratedReturnKind = "value" | "oop" | "object";

export interface GemStoneClassMetadata {
  className: string;
  target: Function;
  selectors: Map<string | symbol, string>;
}

export interface RenderGeneratedFunctionOptions {
  exportedName: string;
  className: string;
  selector: string;
  argNames: string[];
  returnKind?: GeneratedReturnKind;
}

export interface RenderGeneratedModuleOptions {
  functions: readonly RenderGeneratedFunctionOptions[];
  banner?: string | false;
}

const classMetadata = new WeakMap<Function, GemStoneClassMetadata>();

export function GemStoneClass(className: string): ClassDecorator {
  return (target) => {
    const existing = classMetadata.get(target);
    classMetadata.set(target, {
      className,
      target,
      selectors: existing?.selectors ?? new Map(),
    });
  };
}

export function GemStoneSelector(selector: string): MethodDecorator {
  return (target, propertyKey) => {
    const ctor = typeof target === "function" ? target : target.constructor;
    const metadata = classMetadata.get(ctor) ?? {
      className: ctor.name,
      target: ctor,
      selectors: new Map<string | symbol, string>(),
    };
    metadata.selectors.set(propertyKey, selector);
    classMetadata.set(ctor, metadata);
  };
}

export function metadataFor(target: Function): GemStoneClassMetadata | undefined {
  return classMetadata.get(target);
}

export function inferSelector(methodName: string, arity: number): string {
  if (arity <= 0) return methodName;
  if (arity === 1) return `${methodName}:`;
  throw new Error(
    `Cannot infer Smalltalk selector for ${methodName} with ${arity} arguments. ` +
      "Use @GemStoneSelector(\"keyword:selector:\").",
  );
}

export function sendGenerated(
  session: Session,
  className: string,
  selector: string,
  args?: readonly GemStoneArgument[],
): Promise<MarshalledValue>;
export function sendGenerated(
  session: Session,
  className: string,
  selector: string,
  args: readonly GemStoneArgument[] | undefined,
  returnKind: "value",
): Promise<MarshalledValue>;
export function sendGenerated(
  session: Session,
  className: string,
  selector: string,
  args: readonly GemStoneArgument[] | undefined,
  returnKind: "oop",
): Promise<Oop>;
export function sendGenerated(
  session: Session,
  className: string,
  selector: string,
  args: readonly GemStoneArgument[] | undefined,
  returnKind: "object",
): Promise<TypedOop<unknown>>;
export async function sendGenerated(
  session: Session,
  className: string,
  selector: string,
  args: readonly GemStoneArgument[] = [],
  returnKind: GeneratedReturnKind = "value",
): Promise<MarshalledValue | Oop | TypedOop<unknown>> {
  const kind = assertReturnKind(returnKind);
  if (kind === "object") {
    return session.classRef(className).sendObject(selector, ...args);
  }
  const receiver = await session.resolveSymbol(className);
  if (kind === "oop") {
    return session.performWith(receiver, selector, ...args);
  }
  return session.performValueWith(receiver, selector, ...args);
}

export function renderGeneratedFunction(options: RenderGeneratedFunctionOptions): string {
  const exportedName = assertIdentifier(options.exportedName, "exportedName");
  const argNames = options.argNames.map((arg) => assertIdentifier(arg, "argName"));
  const returnKind = assertReturnKind(options.returnKind ?? "value");
  assertUniqueArgNames(argNames);
  const params = ["session", ...argNames].join(", ");
  const forwardedArgs = argNames.length ? `, ${argNames.join(", ")}` : "";

  if (returnKind === "object") {
    return [
      `export async function ${exportedName}(${params}) {`,
      `  return session.classRef(${JSON.stringify(options.className)}).sendObject(${JSON.stringify(options.selector)}${forwardedArgs});`,
      `}`,
      "",
    ].join("\n");
  }

  const method = returnKind === "oop" ? "performWith" : "performValueWith";
  return [
    `export async function ${exportedName}(${params}) {`,
    `  const receiver = await session.resolveSymbol(${JSON.stringify(options.className)});`,
    `  return session.${method}(receiver, ${JSON.stringify(options.selector)}${forwardedArgs});`,
    `}`,
    "",
  ].join("\n");
}

export function renderGeneratedModule(options: RenderGeneratedModuleOptions): string {
  if (!Array.isArray(options.functions)) {
    throw new TypeError("Generated module functions must be an array.");
  }
  const chunks = options.banner === false ? [] : [
    options.banner ?? "// Generated by gemstone-js codegen. Do not edit.",
    "",
  ];
  for (const fn of options.functions) {
    chunks.push(renderGeneratedFunction(fn).trimEnd(), "");
  }
  return chunks.join("\n");
}

function assertReturnKind(value: unknown): GeneratedReturnKind {
  if (value === "value" || value === "oop" || value === "object") return value;
  throw new RangeError(`Generated return kind must be "value", "oop", or "object": ${String(value)}`);
}

function assertIdentifier(value: string, field: string): string {
  if (!/^[A-Za-z_$][A-Za-z0-9_$]*$/.test(value) || RESERVED_JS_WORDS.has(value)) {
    throw new RangeError(`Generated ${field} must be a valid JavaScript identifier: ${value}`);
  }
  return value;
}

function assertUniqueArgNames(argNames: readonly string[]): void {
  const seen = new Set<string>();
  for (const name of argNames) {
    if (seen.has(name)) {
      throw new RangeError(`Generated function argument names must be unique: ${name}`);
    }
    seen.add(name);
  }
}

const RESERVED_JS_WORDS = new Set([
  "await",
  "break",
  "case",
  "catch",
  "class",
  "const",
  "continue",
  "debugger",
  "default",
  "delete",
  "do",
  "else",
  "enum",
  "export",
  "extends",
  "false",
  "finally",
  "for",
  "function",
  "if",
  "import",
  "in",
  "instanceof",
  "let",
  "new",
  "null",
  "return",
  "super",
  "switch",
  "this",
  "throw",
  "true",
  "try",
  "typeof",
  "var",
  "void",
  "while",
  "with",
  "yield",
]);
