export {
  BASELINE_MAINTENANCE_SCHEMA_VERSION,
  BASELINE_MANIFEST_SCHEMA_VERSION,
  BASELINE_REGISTRATION_SCHEMA_VERSION,
  BASELINE_SELECTION_SCHEMA_VERSION,
  BASELINE_MANIFEST_SCHEMA_PATH,
  BENCHMARK_COMPARISON_SCHEMA_VERSION,
  BENCHMARK_REPORT_SCHEMA_PATH,
  BENCHMARK_REPORT_SCHEMA_VERSION,
  COMPARABLE_METADATA_FIELDS,
  BenchmarkBaselineError,
  BenchmarkCliUsageError,
  compareBenchmarkReports,
  formatBenchmarkComparison,
  loadBenchmarkReport,
  pruneBenchmarkBaselineManifest,
  registerBenchmarkBaseline,
  runBenchmarkBaselinesCli,
  runBenchmarkCompareCli,
  runBenchmarkRegisterCli,
  selectBenchmarkBaseline,
  type BaselineManifestMaintenanceReport,
  type BaselineRegistrationReport,
  type BaselineSelectionReport,
  type BenchmarkCliIo,
  type BenchmarkComparisonReport,
  type BenchmarkComparisonRow,
  type BenchmarkComparisonStatus,
  type BenchmarkMetadataField,
  type BenchmarkReport,
  type BenchmarkResultRow,
  type BenchmarkThresholdScope,
  type CompareBenchmarkReportsOptions,
  type PruneBaselineManifestOptions,
  type RegisterBaselineOptions,
} from "./benchmark-baselines.ts";
export {
  DEFAULT_BENCHMARK_ENTRIES,
  DEFAULT_BENCHMARK_SEARCH_RUNS,
  DEFAULT_BENCHMARK_SUITES,
  OFFLINE_BENCHMARK_SUITES,
  BenchmarkRunError,
  BenchmarksCliUsageError,
  benchmarksCliUsage,
  buildBenchmarkReport,
  formatBenchmarkResults,
  runBenchmarkSuite,
  runBenchmarksCli,
  selectedBenchmarkSuitesRequireLive,
  type BenchmarkReportOptions,
  type BenchmarkRunOptions,
  type BenchmarkSessionFactory,
  type BenchmarkSuiteName,
  type BenchmarksCliIo,
} from "./benchmarks.ts";
export {
  BOOTSTRAP_ARTIFACTS,
  BOOTSTRAP_MARKER_KEY,
  BOOTSTRAP_VERSION,
  BootstrapCliUsageError,
  auditBootstrap,
  bootstrapCliUsage,
  bootstrapGemStone,
  bootstrapSource,
  formatBootstrapPlan,
  formatBootstrapResult,
  formatBootstrapStatuses,
  runBootstrapCli,
  type BootstrapArtifact,
  type BootstrapArtifactStatus,
  type BootstrapCliIo,
  type BootstrapCliSession,
  type BootstrapOptions,
  type BootstrapResult,
} from "./bootstrap.ts";
export {
  Session,
  GemStoneClassRef,
  ManagedOop,
  TypedOop,
  resolveSessionConfig,
  type ArrayOopReadbackOptions,
  type ArrayReadbackOptions,
  type GemStoneArrayArgument,
  type GemStoneArrayIndexMap,
  type GemStoneArgument,
  type GemStoneDictionaryArgument,
  type MarshalledArray,
  type MarshalledDictionary,
  type MarshalledValue,
} from "./client.ts";
export {
  OOP_ASCII_NUL,
  OOP_FALSE,
  OOP_ILLEGAL,
  OOP_NIL,
  OOP_TRUE,
  boolToOop,
  charToOop,
  isBoolean,
  isChar,
  isIllegal,
  isNil,
  isSmallint,
  isSmalldouble,
  marshalImmediateOop,
  oop,
  oopToBool,
  oopToChar,
  oopToHex,
  oopToSmallint,
  rawOop,
  smallintToOop,
  type Oop,
} from "./oop.ts";
export {
  GemStoneClass,
  GemStoneSelector,
  inferGeneratedReturnKind,
  inferSelector,
  metadataFor,
  renderGeneratedFunction,
  renderGeneratedModule,
  sendGenerated,
  validateGeneratedFunctionOptions,
  validateGeneratedModuleOptions,
  type GeneratedReturnKind,
  type GeneratedImportSpec,
  type GeneratedNamedImportSpec,
  type GemStoneClassMetadata,
  type RenderGeneratedFunctionOptions,
  type RenderGeneratedModuleOptions,
} from "./codegen.ts";
export { PersistentRoot } from "./persistent-root.ts";
export { GsDict } from "./gsdict.ts";
export {
  RcCounter,
  RcKeyValueDictionary,
  RcQueue,
  RcCounter as RCCounter,
  RcKeyValueDictionary as RCHash,
  RcQueue as RCQueue,
  type RcCounterDecrementOptions,
} from "./reduced-conflict.ts";
export {
  GSTORE_ROOT,
  GStore,
  GStoreAbortTransaction,
  GStoreError,
  GStoreTransaction,
  type GStoreJsonValue,
  type GStoreTransactionOptions,
} from "./gstore.ts";
export {
  DEFAULT_MIGRATION_LOCK,
  DEFAULT_MIGRATION_LOCK_STALE_AFTER_SECONDS,
  DEFAULT_MIGRATION_ROOT,
  MigrationError,
  MigrationsCliUsageError,
  RecordingMigrationSession,
  acquireMigrationLock,
  appliedMigrations,
  currentVersion,
  downgrade,
  formatMigrationPlan,
  formatMigrationResult,
  formatMigrationStatus,
  migrationStatus,
  migrationStepsFromManifest,
  migrationsCliUsage,
  planDowngrade,
  planUpgrade,
  releaseMigrationLock,
  runMigrationsCli,
  upgrade,
  validateMigrationState,
  type MigrationCallback,
  type MigrationInput,
  type MigrationLock,
  type MigrationLockOptions,
  type MigrationRecord,
  type MigrationResult,
  type MigrationRunOptions,
  type MigrationStatus,
  type MigrationStep,
  type MigrationsCliIo,
} from "./migrations.ts";
export { GSCollection, type ComparisonOp, type GSCollectionIndexKind, type GSCollectionIndexOptions } from "./query.ts";
export {
  OBJECT_LOG_LEVELS,
  ObjectLog,
  parseObjectLogEntries,
  type ObjectLogAddOptions,
  type ObjectLogEntry,
  type ObjectLogLevelName,
  type ObjectLogPriority,
} from "./object-log.ts";
export {
  PooledSession,
  SessionPool,
  type PoolConfig,
  type PooledSessionReleaseOptions,
  type PoolWithSessionOptions,
} from "./pool.ts";
export { gemstoneExpress, type ExpressGemStoneOptions } from "./adapters/express.ts";
export { gemstoneFastify, type FastifyGemStoneOptions } from "./adapters/fastify.ts";
export { gemstoneHono, type HonoGemStoneOptions } from "./adapters/hono.ts";
export {
  NULL_METRICS,
  NULL_SPAN,
  NULL_SPAN_CONTEXT,
  NULL_TRACER,
  InMemoryMetrics,
  InMemoryTracer,
  NullMetrics,
  NullTracer,
  OpenTelemetryTracer,
  observe,
  type MetricsCollector,
  type MetricLabels,
  type RecordedMetricDuration,
  type RecordedMetricIncrement,
  type RecordedSpan,
  type Span,
  type SpanAttributes,
  type SpanContext,
  type Tracer,
} from "./observability.ts";
export { SerializedGciRuntime, serializeGciRuntime } from "./runtime/serialized.ts";
export {
  decodeEscapedField,
  escapedFieldEncoderSource,
  escapeSmalltalkStringLiteral,
  objectForOopSource,
  validateGemStoneGlobalName,
} from "./smalltalk-source.ts";
export {
  createGciRuntime,
  getGciRuntime,
  setGciRuntimeFactoryForTesting,
  setGciRuntimeForTesting,
} from "./runtime/index.ts";
export {
  GemStoneConfigurationError,
  GemStoneError,
  type GciErrorInfo,
  type GciRuntime,
  type GemStoneClassDescription,
  type GemStoneDumpOptions,
  type GemStoneDumpValue,
  type GemStoneIndexedFieldInspection,
  type GemStoneInspection,
  type GemStoneObjectDump,
  type GemStoneObjectReference,
  type GemStoneSlotInspection,
  type LoginOptions,
  type PoolStats,
  type ResolvedSessionConfig,
  type RuntimeName,
  type SessionConfig,
  type SymDictLookup,
} from "./types.ts";
