export {
  Session,
  GemStoneClassRef,
  ManagedOop,
  TypedOop,
  resolveSessionConfig,
  type ArrayReadbackOptions,
  type GemStoneArrayArgument,
  type GemStoneArgument,
  type GemStoneDictionaryArgument,
  type MarshalledArray,
  type MarshalledValue,
} from "./client.ts";
export {
  OOP_ASCII_NUL,
  OOP_FALSE,
  OOP_ILLEGAL,
  OOP_NIL,
  OOP_TRUE,
  boolToOop,
  charToOop,
  isBoolean,
  isChar,
  isIllegal,
  isNil,
  isSmallint,
  isSmalldouble,
  marshalImmediateOop,
  oop,
  oopToBool,
  oopToChar,
  oopToHex,
  oopToSmallint,
  rawOop,
  smallintToOop,
  type Oop,
} from "./oop.ts";
export {
  GemStoneClass,
  GemStoneSelector,
  inferGeneratedReturnKind,
  inferSelector,
  metadataFor,
  renderGeneratedFunction,
  renderGeneratedModule,
  sendGenerated,
  validateGeneratedFunctionOptions,
  validateGeneratedModuleOptions,
  type GeneratedReturnKind,
  type GeneratedImportSpec,
  type GeneratedNamedImportSpec,
  type GemStoneClassMetadata,
  type RenderGeneratedFunctionOptions,
  type RenderGeneratedModuleOptions,
} from "./codegen.ts";
export { PersistentRoot } from "./persistent-root.ts";
export { GsDict } from "./gsdict.ts";
export { GSCollection, type ComparisonOp, type GSCollectionIndexKind, type GSCollectionIndexOptions } from "./query.ts";
export {
  PooledSession,
  SessionPool,
  type PoolConfig,
  type PooledSessionReleaseOptions,
  type PoolWithSessionOptions,
} from "./pool.ts";
export { gemstoneExpress, type ExpressGemStoneOptions } from "./adapters/express.ts";
export { gemstoneFastify, type FastifyGemStoneOptions } from "./adapters/fastify.ts";
export { gemstoneHono, type HonoGemStoneOptions } from "./adapters/hono.ts";
export {
  NULL_METRICS,
  NULL_SPAN,
  NULL_SPAN_CONTEXT,
  NULL_TRACER,
  InMemoryMetrics,
  InMemoryTracer,
  NullMetrics,
  NullTracer,
  OpenTelemetryTracer,
  observe,
  type MetricsCollector,
  type MetricLabels,
  type RecordedMetricDuration,
  type RecordedMetricIncrement,
  type RecordedSpan,
  type Span,
  type SpanAttributes,
  type SpanContext,
  type Tracer,
} from "./observability.ts";
export { SerializedGciRuntime, serializeGciRuntime } from "./runtime/serialized.ts";
export {
  createGciRuntime,
  getGciRuntime,
  setGciRuntimeFactoryForTesting,
  setGciRuntimeForTesting,
} from "./runtime/index.ts";
export {
  GemStoneConfigurationError,
  GemStoneError,
  type GciErrorInfo,
  type GciRuntime,
  type GemStoneIndexedFieldInspection,
  type GemStoneInspection,
  type GemStoneSlotInspection,
  type LoginOptions,
  type PoolStats,
  type ResolvedSessionConfig,
  type RuntimeName,
  type SessionConfig,
  type SymDictLookup,
} from "./types.ts";
